Class Classes.Models.Address Extends %Persistent
{

Storage Default
{
<Data name="AddressDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^Classes.Models.AddressD</DataLocation>
<DefaultData>AddressDefaultData</DefaultData>
<IdLocation>^Classes.Models.AddressD</IdLocation>
<IndexLocation>^Classes.Models.AddressI</IndexLocation>
<StreamLocation>^Classes.Models.AddressS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
