Class notes.Production.Production Extends Ens.Production
{

XData ProductionDefinition
{
<Production Name="notes.Production.Production" LogGeneralTraceEvents="false">
  <Description></Description>
  <ActorPoolSize>2</ActorPoolSize>
  <Item Name="notes.Production.BS.SOAP" Category="" ClassName="notes.Production.BS.SOAP" PoolSize="0" Enabled="true" Foreground="false" Comment="" LogTraceEvents="false" Schedule="">
  </Item>
</Production>
}

}
